// <auto-generated />
using JwDelivery.Data.SqlServer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace JwDelivery.Data.SqlServer.Migrations
{
    [DbContext(typeof(JwDeliveryContext))]
    partial class JwDeliveryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JwDelivery.Data.SqlServer.Models.Employee", b =>
                {
                    b.Property<long>("EmployeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Gender")
                        .HasMaxLength(10);

                    b.Property<DateTime>("HireDate");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50);

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(15);

                    b.Property<DateTime?>("ReleasedDate");

                    b.Property<string>("Title")
                        .HasMaxLength(10);

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("JwDelivery.Data.SqlServer.Models.EmployeeAddress", b =>
                {
                    b.Property<long>("EmployeeAddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .HasMaxLength(30);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("EmployeeId");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("EmployeeAddressId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeAddress");
                });

            modelBuilder.Entity("JwDelivery.Data.SqlServer.Models.EmployeeAudit", b =>
                {
                    b.Property<long>("EmployeeAuditId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuditUser")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("EmployeeId");

                    b.Property<long>("StatusId");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("EmployeeAuditId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StatusId")
                        .IsUnique();

                    b.ToTable("EmployeeAudit");
                });

            modelBuilder.Entity("JwDelivery.Data.SqlServer.Models.EmployeeRate", b =>
                {
                    b.Property<long>("EmployeeRateId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("EmployeeId");

                    b.Property<long>("RateTypeId");

                    b.Property<decimal>("Value");

                    b.HasKey("EmployeeRateId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RateTypeId")
                        .IsUnique();

                    b.ToTable("EmployeeRate");
                });

            modelBuilder.Entity("JwDelivery.Data.SqlServer.Models.EmployeeRateAudit", b =>
                {
                    b.Property<long>("EmployeeRateAuditId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuditUser")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("EmployeeRateId");

                    b.Property<long>("StatusId");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("EmployeeRateAuditId");

                    b.HasIndex("EmployeeRateId")
                        .IsUnique();

                    b.HasIndex("StatusId")
                        .IsUnique();

                    b.ToTable("EmployeeRateAudit");
                });

            modelBuilder.Entity("JwDelivery.Data.SqlServer.Models.RateType", b =>
                {
                    b.Property<long>("RateTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("RateTypeId");

                    b.ToTable("List_RateType");
                });

            modelBuilder.Entity("JwDelivery.Data.SqlServer.Models.Status", b =>
                {
                    b.Property<long>("StatusId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("StatusId");

                    b.ToTable("List_Status");
                });

            modelBuilder.Entity("JwDelivery.Data.SqlServer.Models.EmployeeAddress", b =>
                {
                    b.HasOne("JwDelivery.Data.SqlServer.Models.Employee", "Employee")
                        .WithMany("Addresses")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("ForeignKey_Employee_Address")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JwDelivery.Data.SqlServer.Models.EmployeeAudit", b =>
                {
                    b.HasOne("JwDelivery.Data.SqlServer.Models.Employee", "Employee")
                        .WithMany("EmployeeAudits")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("ForeignKey_EmployeeAudit_Employee")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JwDelivery.Data.SqlServer.Models.Status", "Status")
                        .WithOne()
                        .HasForeignKey("JwDelivery.Data.SqlServer.Models.EmployeeAudit", "StatusId")
                        .HasConstraintName("ForeignKey_EmployeeAudit_Status")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JwDelivery.Data.SqlServer.Models.EmployeeRate", b =>
                {
                    b.HasOne("JwDelivery.Data.SqlServer.Models.Employee", "Employee")
                        .WithMany("EmployeeRates")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("ForeignKey_Employee_Rate")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JwDelivery.Data.SqlServer.Models.RateType", "RateType")
                        .WithOne()
                        .HasForeignKey("JwDelivery.Data.SqlServer.Models.EmployeeRate", "RateTypeId")
                        .HasConstraintName("ForeignKey_Employee_RateType")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JwDelivery.Data.SqlServer.Models.EmployeeRateAudit", b =>
                {
                    b.HasOne("JwDelivery.Data.SqlServer.Models.EmployeeRate", "EmployeeRate")
                        .WithOne()
                        .HasForeignKey("JwDelivery.Data.SqlServer.Models.EmployeeRateAudit", "EmployeeRateId")
                        .HasConstraintName("ForeignKey_EmployeeRateAudit_EmployeeRate")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JwDelivery.Data.SqlServer.Models.Status", "Status")
                        .WithOne()
                        .HasForeignKey("JwDelivery.Data.SqlServer.Models.EmployeeRateAudit", "StatusId")
                        .HasConstraintName("ForeignKey_EmployeeRateAudit_Status")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
